# Generated by Django 5.1.4 on 2026-02-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notification_review_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("reply", "Reply"),
                    ("message", "Message"),
                    ("review", "Review"),
                    ("mention", "Mention"),
                ],
                max_length=10,
            ),
        ),
    ]
