# Generated by Django 5.1.4 on 2026-03-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("reply", "Reply"),
                    ("message", "Message"),
                    ("review", "Review"),
                    ("mention", "Mention"),
                    ("follow", "Follow"),
                ],
                max_length=10,
            ),
        ),
    ]
