# Generated by Django 5.1.4 on 2025-03-11 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="encrypted_content",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
