# Generated by Django 5.1.4 on 2025-04-21 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_message_encrypted_content_alter_message_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inbox",
            options={"verbose_name_plural": "Inboxes"},
        ),
    ]
