# Generated by Django 5.1.4 on 2026-02-09 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_message_is_read"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inbox",
            options={
                "ordering": ["-last_message_at", "-updated_at"],
                "verbose_name_plural": "Inboxes",
            },
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
        migrations.AddField(
            model_name="inbox",
            name="last_message_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inbox",
            name="last_message_sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inbox",
            name="last_message_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="inbox",
            name="unread_by",
            field=models.ManyToManyField(
                blank=True, related_name="unread_inboxes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="inbox",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
