# Generated by Django 5.1.4 on 2025-04-21 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"verbose_name_plural": "Media"},
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
