# Generated by Django 5.1.4 on 2026-06-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_hashtag_remove_post_tags_post_hashtags"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="hashtags",
            field=models.ManyToManyField(blank=True, to="blog.hashtag"),
        ),
    ]
