# Generated by Django 5.1.4 on 2025-08-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_rename_user_review_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
