# Generated by Django 5.1.4 on 2026-08-19 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
    ]
