# Generated by Django 5.1.4 on 2026-08-15 10:36 ("users", "0001_initial"),

from django.db import migrations


SECTORS = [
    "Crop Farming",
    "Livestock Farming",
    "Poultry Farming",
    "Dairy Farming",
    "Aquaculture",
    "Horticulture",
    "Fruit Farming",
    "Vegetable Farming",
    "Grain Farming",
    "Cereal Farming",
    "Legume Farming",
    "Root and Tuber Farming",
    "Oilseed Farming",
    "Sugarcane Farming",
    "Viticulture",
    "Floriculture",
    "Beekeeping",
    "Agroforestry",
    "Organic Farming",
    "Mixed Farming",
]


def create_sectors(apps, schema_editor):
    Sector = apps.get_model("users", "Sector")

    for order, name in enumerate(SECTORS, start=1):
        Sector.objects.get_or_create(
            name=name,
            defaults={"order": order}
        )


def remove_sectors(apps, schema_editor):
    Sector = apps.get_model("users", "Sector")

    Sector.objects.filter(
        name__in=SECTORS
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_sectors,
            remove_sectors
        ),
    ]
