# Generated by Django 5.1.4 on 2024-12-22 18:17

from django.db import migrations

def populate_sectors(apps, schema_editor):
    Sector = apps.get_model('users', 'Sector')
    default_sectors = [
        "Livestock",
        "Crop Farming",
        "Aquaculture",
        "Horticulture",
        "Agroforestry",
        "Poultry Farming",
    ]
    for sector_name in default_sectors:
        Sector.objects.get_or_create(name=sector_name)
        
class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_sectors),
    ]
