# Generated by Django 5.1.4 on 2026-08-19 05:40

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_populate_sectors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="background_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="background_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.profile_picture_upload_to
            ),
        ),
    ]
