# Generated by Django 5.1.4 on 2024-12-22 18:26

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20241222_2017"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default.jpg",
                null=True,
                upload_to=users.models.profile_picture_upload_to,
            ),
        ),
    ]
