# Generated by Django 5.1.4 on 2025-08-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="background_picture",
            field=models.ImageField(
                blank=True,
                default="background_pictures/default.jpg",
                null=True,
                upload_to="background_pictures/",
            ),
        ),
    ]
