# Generated by Django 5.1.4 on 2025-08-23 15:02

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_profile_background_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default.png",
                null=True,
                upload_to=users.models.profile_picture_upload_to,
            ),
        ),
    ]
