# Generated by Django 5.1.4 on 2026-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_customuser_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
