# Generated by Django 5.1.4 on 2026-08-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sector",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="sector",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
