# Generated by Django 5.1.4 on 2026-08-06 11:44

from django.db import migrations

from django.db import migrations


def create_sectors(apps, schema_editor):

    Sector = apps.get_model(
        "users",
        "Sector"
    )


    sectors = [
        "Livestock",
        "Crop Farming",
        "Aquaculture",
        "Horticulture",
        "Agroforestry",
        "Poultry Farming",
        "Dairy Farming",
        "Beekeeping",
        "Viticulture(Grapes & Wine)",
        "Sericulture(Silk Production)",
        "Mushroom Farming",
        "Organic Farming",
        "Greenhouse Farming",
        "Hydroponics",
        "Arable Farming",
        "Mixed Farming",
        "Fish Farming",
        "Goat Farming",
        "Sheep Farming",
        "Pig Farming",
    ]


    for sector in sectors:
        Sector.objects.get_or_create(
            name=sector
        )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_sector_options_sector_order"),
    ]

    operations = [
        migrations.RunPython(
            create_sectors
        ),
    ]
